# Testing Environments
#-----------------------------------------------------------------------
---
.lint_tests: &lint_tests
  stage: 'validation'
  tags: ['docker']
  extends: '.setup_bundler_env'
  script:
    - 'bundle exec rake syntax'
    - 'bundle exec rake lint'
    - 'bundle exec rake metadata_lint'

.unit_tests: &unit_tests
  stage: 'validation'
  tags: ['docker']
  extends: '.setup_bundler_env'
  script:
    - 'bundle exec rake spec'

.acceptance_base: &acceptance_base
  stage: 'acceptance'
  tags: ['beaker']
  extends: '.setup_bundler_env'

.compliance_base: &compliance_base
  stage: 'compliance'
  tags: ['beaker']
  extends: '.setup_bundler_env'

# Linting
#-----------------------------------------------------------------------

pup5-lint:
  extends: '.pup_5'
  <<: *lint_tests

pup6-lint:
  extends: '.pup_6'
  <<: *lint_tests

# Unit Tests
#-----------------------------------------------------------------------

pup5-unit:
  extends: '.pup_5'
  <<: *unit_tests

pup5.5.10-unit:
  extends: '.pup_5_5_10'
  <<: *unit_tests

pup6-unit:
  extends: '.pup_6'
  <<: *unit_tests

# Acceptance tests
# ==============================================================================
pup5.5.10:
  extends: '.pup_5_5_10'
  <<: *acceptance_base
  script:
    - 'bundle exec rake beaker:suites'

pup5.5.10-fips:
  extends: '.pup_5_5_10'
  <<: *acceptance_base
  script:
    - 'BEAKER_fips=yes bundle exec rake beaker:suites'

pup5.5.10-oel-combined-x64:
  extends: '.pup_5_5_10'
  <<: *acceptance_base
  script:
    - 'bundle exec rake beaker:suites[default,oel-combined-x64]'

pup5.5.10-oel-combined-x64-fips:
  extends: '.pup_5_5_10'
  <<: *acceptance_base
  script:
    - 'BEAKER_fips=yes bundle exec rake beaker:suites[default,oel-combined-x64]'

pup6:
  extends: '.pup_6'
  <<: *acceptance_base
  script:
    - 'bundle exec rake beaker:suites'

pup6-fips:
  extends: '.pup_6'
  <<: *acceptance_base
  script:
    - 'BEAKER_fips=yes bundle exec rake beaker:suites'
