# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2019.0/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.3      5.5.10   2.4.5  TBD***
# PE 2018.1.7   5.5.10   2.4.5  2020-05 (LTS)***
# PE 2019.0     6.0      2.5.1  2019-08-31^^^
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
include:
  - local: '/gitlab-templates/.templates/stages.yml'
  - local: '/gitlab-templates/.templates/variables.yml'
  - local: '/gitlab-templates/.templates/setup_bundler_env.yml'
  - local: '/gitlab-templates/.templates/only_with_simp_full_matrix.yml'
  - local: '/gitlab-templates/.templates/test_environments.yml'


# Puppet Versions
#-----------------------------------------------------------------------

.pup_5:
  extends: .pup5_ruby_version
  variables:
    PUPPET_VERSION: '~> 5.0'

.pup_5_5_10:
  extends: .pup5_ruby_version
  variables:
    PUPPET_VERSION: '5.5.10'

.pup_6:
  extends: .pup6_ruby_version
  variables:
    PUPPET_VERSION: '~> 6.0'



# Pipeline / testing matrix
#=======================================================================

sanity_checks:
  extends: .pup_5
  extends: .setup_bundler_env
  stage: 'sanity'
  tags: ['docker']
  script:
    - 'if `hash apt-get`; then apt-get update; fi'
    - 'if `hash apt-get`; then apt-get install -y rpm; fi'
    - 'bundle exec rake check:dot_underscore'
    - 'bundle exec rake check:test_file'
    - 'bundle exec rake pkg:check_version'
    - 'bundle exec rake pkg:compare_latest_tag'
    - 'bundle exec rake pkg:create_tag_changelog'
    - 'bundle exec puppet module build'

# Linting
#-----------------------------------------------------------------------

pup5-lint:
  extends: .pup_5
  extends: .lint_tests


# Unit Tests
#-----------------------------------------------------------------------

pup5-unit:
  extends: .pup_5
  extends: .unit_tests

pup5.5.10-unit:
  extends: .pup_5_5_10
  extends: .unit_tests


# Acceptance tests
# ==============================================================================
pup5.5.10:
  extends: .pup_5_5_10
  extends: .acceptance_base
  script:
    - 'bundle exec rake beaker:suites'


