---
include:
  - .templates/acceptance_tests.yml
  - .templates/linting.yml
  - .templates/only_with_simp_full_matrix.yml
  - .templates/pipeline_testing_matrix.yml
  - .templates/pup_versions.yml
  - .templates/setup_bundler_env.yml
  - .templates/stages.yml
  - .templates/test_environments.yml
  - .templates/unit_tests.yml
  - .templates/variables.yml
