---
include:
  - local: '/gitlab-templates/.templates/stages.yml'
  - local: '/gitlab-templates/.templates/variables.yml'
  - local: '/gitlab-templates/.templates/setup_bundler_env.yml'
  - local: '/gitlab-templates/.templates/only_with_simp_full_matrix.yml'
  - local: '/gitlab-templates/.templates/linting.yml'
  - local: '/gitlab-templates/.templates/pipeline_testing_matrix.yml'
  - local: '/gitlab-templates/.templates/pup_versions.yml'
  - local: '/gitlab-templates/.templates/test_environments.yml'
  - local: '/gitlab-templates/.templates/unit_tests.yml'
  - local: '/gitlab-templates/.templates/acceptance_tests.yml'
