---
include:
  - acceptance_tests.yml
  - linting.yml
  - only_with_simp_full_matrix.yml
  - pipeline_testing_matrix.yml
  - pup_versions.yml
  - setup_bundler_env.yml
  - stages.yml
  - test_environments.yml
  - unit_tests.yml
  - variables.yml
