---
include:
  - local: '.templates/acceptance_tests.yml'
  - local: '.templates/linting.yml'
  - local: '.templates/only_with_simp_full_matrix.yml'
  - local: '.templates/pipeline_testing_matrix.yml'
  - local: '.templates/pup_versions.yml'
  - local: '.templates/setup_bundler_env.yml'
  - local: '.templates/stages.yml'
  - local: '.templates/test_environments.yml'
  - local: '.templates/unit_tests.yml'
  - local: '.templates/variables.yml'
