# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2019.0/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.3      5.5.10   2.4.5  TBD***
# PE 2018.1.7   5.5.10   2.4.5  2020-05 (LTS)***
# PE 2019.0     6.0      2.5.1  2019-08-31^^^
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
include:
  - local: '/gitlab-templates/.templates/stages.yml'
  - local: '/gitlab-templates/.templates/variables.yml'
  - local: '/gitlab-templates/.templates/setup_bundler_env.yml'
  - local: '/gitlab-templates/.templates/only_with_simp_full_matrix.yml'
  - local: '/gitlab-templates/.templates/test_environments.yml'


# Puppet Versions
#-----------------------------------------------------------------------

.pup_5: &pup_5
  image: 'ruby:2.4.5'
  variables:
    PUPPET_VERSION: '~> 5.0'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    MATRIX_RUBY_VERSION: '2.4.5'

.pup_5_5_10: &pup_5_5_10
  image: 'ruby:2.4.5'
  variables:
    PUPPET_VERSION: '5.5.10'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    MATRIX_RUBY_VERSION: '2.4.5'

.pup_6: &pup_6
  image: 'ruby:2.5.1'
  variables:
    PUPPET_VERSION: '~> 6.0'
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    MATRIX_RUBY_VERSION: '2.5.1'



# Pipeline / testing matrix
#=======================================================================

sanity_checks:
  <<: *pup_5
  extends: .setup_bundler_env
  stage: 'sanity'
  tags: ['docker']
  script:
    - 'if `hash apt-get`; then apt-get update; fi'
    - 'if `hash apt-get`; then apt-get install -y rpm; fi'
    - 'bundle exec rake check:dot_underscore'
    - 'bundle exec rake check:test_file'
    - 'bundle exec rake pkg:check_version'
    - 'bundle exec rake pkg:compare_latest_tag'
    - 'bundle exec rake pkg:create_tag_changelog'
    - 'bundle exec puppet module build'

# Linting
#-----------------------------------------------------------------------

pup5-lint:
  <<: *pup_5
  extends: .lint_tests

pup6-lint:
  <<: *pup_6
  extends: .lint_tests

# Unit Tests
#-----------------------------------------------------------------------

pup5-unit:
  <<: *pup_5
  extends: .unit_tests

pup5.5.10-unit:
  <<: *pup_5_5_10
  extends: .unit_tests

pup6-unit:
  <<: *pup_6
  extends: .unit_tests

# Acceptance tests
# ==============================================================================
pup5.5.10:
  <<: *pup_5_5_10
  extends: .acceptance_base
  script:
    - 'bundle exec rake beaker:suites'

pup5.5.10-fips:
  <<: *pup_5_5_10
  extends: .acceptance_base
  script:
    - 'BEAKER_fips=yes bundle exec rake beaker:suites'

pup5.5.10-oel-combined-x64:
  <<: *pup_5_5_10
  extends: .acceptance_base
  script:
    - 'bundle exec rake beaker:suites[default,oel-combined-x64]'

pup5.5.10-oel-combined-x64-fips:
  <<: *pup_5_5_10
  extends: .acceptance_base
  extends: .only_with_SIMP_FULL_MATRIX
  script:
    - 'BEAKER_fips=yes bundle exec rake beaker:suites[default,oel-combined-x64]'

pup6:
  <<: *pup_6
  extends: .acceptance_base
  script:
    - 'bundle exec rake beaker:suites'

pup6-fips:
  <<: *pup_6
  extends: .acceptance_base
  script:
    - 'BEAKER_fips=yes bundle exec rake beaker:suites'
