# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2019.0/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.3      5.5.10   2.4.5  TBD***
# PE 2018.1.7   5.5.10   2.4.5  2020-05 (LTS)***
# PE 2019.0     6.0      2.5.1  2019-08-31^^^
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
include:
#  - local: '/gitlab-templates/.templates/bundle_and_sanity.yml'
  - local: '/gitlab-templates/.templates/pup_versions.yml'
  - local: '/gitlab-templates/.templates/setup_bundler_env.yml'
  - local: '/gitlab-templates/.templates/stages.yml'
  - local: '/gitlab-templates/.templates/test_environments.yml'
  - local: '/gitlab-templates/.templates/variables.yml'

# unused atm, but keeping because it can be switched in for the tests
  - local: '/gitlab-templates/.templates/only_with_simp_full_matrix.yml'
